### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by kyle-messier** [NIEHS/GeoTox#13]
I think having the word package in the name is a bit redundant. Low priority. Open to suggestions:

- [x] GeoTox
- [ ] GeoToxMap

**Comment by davidmreif** [comment]
I vote 'GeoTox' as a stem for future branches/riff

**Comment by davidmreif** [comment]
(Running list...)
- [ ] Complete replication vignette
- [ ] Analysis of 2x2 scenario table for population example
