### ISSUE TITLE
add unit tests for a goal of 💯 percent coverage

### ISSUE THREAD

**Issue by kyle-messier** [NIEHS/GeoTox#23]

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
@SkylarMarvel I assigned myself to adding unit tests as I wanted some additional practice with this. Of course, feel free to add your own here too if you are so inclined.

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
The following functions need tests:

- [ ] calc_concentration_response.R
- [ ] simulate_exposure.R
- [ ] simulate_inhalation_rate.R
- [ ] obj_GCA.R
- [ ] obj_ECx.R
- [ ] calc_invitro_concentration.R
- [ ] fit_hill.R (bring to 100)
- [ ] obj_hill.R 
- [ ] calc_independent_action.R
- [ ] tcplHillVal.R
- [ ] calc_internal_dose.R
- [ ] tcplHillConc.R

**Comment by SkylarMarvel** [comment]
100% test coverage as of #71
