### ISSUE TITLE
dev-conc-resp vignette has NaN warnings

### ISSUE THREAD

**Issue by kyle-messier** [NIEHS/GeoTox#26]

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
2-parameter hill model fit standard error is showing a NaN warning.

![Image](https://github.com/Spatiotemporal-Exposures-and-Toxicology/GeoToxPackage/assets/127860447/21984f1e-b4f6-4f9c-bda8-fd68f8ed3472)

**Comment by SkylarMarvel** [comment]
Added suppressWarnings to fit_hill.R:
sds <- suppressWarnings(sqrt(diag(solve(-fit$hessian))))
